name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/test-docker:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Checkout second repo
        uses: actions/checkout@v4
        with:
          repository: RishikesavanRamesh/ROS2-DEV
          path: ros2-dev

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            PACKAGE_NAME=${{ env.PACKAGE_NAME }}
          tags: ${{ env.TEST_TAG }}

      - name: Run the Container
        id: run
        env:
          PACKAGE_NAME: Mona Lisa Octocat
        run: |
          docker run \
            --rm ${{ env.TEST_TAG }}

  # test-action:
  #   name: GitHub Actions Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Test Local Action
  #       id: test-action
  #       uses: ./
  #       with:
  #         who-to-greet: Mona Lisa Octocat

  #     - name: Print Output
  #       id: output
  #       run: echo "${{ steps.test-action.outputs.greeting }}"
