name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        ros-distro:
          - humble
          - iron
        package:
          - test1.d

    # # Run a local registry to push to
    # services:
    #   registry:
    #     image: registry:2
    #     ports:
    #       - 5001:5000

    env:
      TEST_TAG: ghcr.io/rishikesavanramesh/test-docker
      ROS_DISTRO: ${{ matrix.ros-distro }}
      PACKAGE_NAME:  ${{ matrix.package }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Checkout second repo
        uses: actions/checkout@v4
        with:
          repository: ros2/demos
          ref: ${{ env.ROS_DISTRO }}
          path: test-folder/test1.d

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            PACKAGE_NAME=${{ env.PACKAGE_NAME }}
          tags: ${{ env.TEST_TAG }}:${{ env.ROS_DISTRO }}

      - name: Run the Container
        id: run
        env:
          PACKAGE_NAME: Mona Lisa Octocat
        run: |
          docker run \
            --rm ${{ env.TEST_TAG }}:${{ env.ROS_DISTRO }}

  # test-action:
  #   name: GitHub Actions Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Test Local Action
  #       id: test-action
  #       uses: ./
  #       with:
  #         who-to-greet: Mona Lisa Octocat

  #     - name: Print Output
  #       id: output
  #       run: echo "${{ steps.test-action.outputs.greeting }}"
